// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZeMrTFX9zc0WZcWeIeFB-6yxJBMSK-4',
    appId: '1:19174580354:web:2c749fd189720df573d49b',
    messagingSenderId: '19174580354',
    projectId: 'authtutorial-16976',
    authDomain: 'authtutorial-16976.firebaseapp.com',
    storageBucket: 'authtutorial-16976.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRNydB8ix1q0eeS3ZE8eIWBcoFsa7RsM',
    appId: '1:19174580354:android:bedfad34f15926c273d49b',
    messagingSenderId: '19174580354',
    projectId: 'authtutorial-16976',
    storageBucket: 'authtutorial-16976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8q3wMZwi82ltq2aA60VAdG_Gv-5rQhbA',
    appId: '1:19174580354:ios:c8d5c405e6b0714473d49b',
    messagingSenderId: '19174580354',
    projectId: 'authtutorial-16976',
    storageBucket: 'authtutorial-16976.appspot.com',
    iosBundleId: 'com.example.ms11Authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8q3wMZwi82ltq2aA60VAdG_Gv-5rQhbA',
    appId: '1:19174580354:ios:c8d5c405e6b0714473d49b',
    messagingSenderId: '19174580354',
    projectId: 'authtutorial-16976',
    storageBucket: 'authtutorial-16976.appspot.com',
    iosBundleId: 'com.example.ms11Authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIZeMrTFX9zc0WZcWeIeFB-6yxJBMSK-4',
    appId: '1:19174580354:web:a1fb8ba342aaee2573d49b',
    messagingSenderId: '19174580354',
    projectId: 'authtutorial-16976',
    authDomain: 'authtutorial-16976.firebaseapp.com',
    storageBucket: 'authtutorial-16976.appspot.com',
  );
}
